# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

deals = []
deals << Deal.create(
	name: "ABC Industries",
	city: "San Francisco",
	state: "CA",
	round_type: "millions",
	entry_year: "2014",
	entry_revenue: "50",
	entry_gp: "25",
	entry_gm: "50",
	entry_EBITDA: "10",
	entry_EBITDA_margin: "20",
	entry_capex: "1",
	entry_fcf: "9",
	leverage_multiple: "5",
	leverage_amount: "50",
	equity_multiple: "5",
	equity_amount: "50",
	purchase_multiple: "10",
	purchase_price: "100",
	exit_year: "2018",
	exit_revenue: "100",
	exit_gp: "50",
	exit_gm: "50",
	exit_EBITDA: "25",
	exit_EBITDA_margin: "25",
	exit_capex: "3",
	exit_fcf: "22",
	exit_multiple: "10",
	exit_price: "250",
	debt_paydown_multiple: "3",
	debt_paydown_amount: "30",
	exit_debt_paydown: "20",
	exit_proceeds: "220",
	coc_return: "4.4",
	irr: "40",
	entry_mult_sensitivity: "1",
	exit_mult_sensitivity: "1"
)

deals << Deal.create(
	name: "Widgets, Inc.",
	city: "Chicago",
	state: "IL",
	round_type: "millions",
	entry_year: "2015",
	entry_revenue: "80",
	entry_gp: "30",
	entry_gm: "37.5",
	entry_EBITDA: "15",
	entry_EBITDA_margin: "18.8",
	entry_capex: "4",
	entry_fcf: "11",
	leverage_multiple: "4",
	leverage_amount: "60",
	equity_multiple: "5",
	equity_amount: "75",
	purchase_multiple: "9",
	purchase_price: "135",
	exit_year: "2019",
	exit_revenue: "120",
	exit_gp: "48",
	exit_gm: "40",
	exit_EBITDA: "30",
	exit_EBITDA_margin: "25",
	exit_capex: "5",
	exit_fcf: "20",
	exit_multiple: "8",
	exit_price: "200",
	debt_paydown_multiple: "3",
	debt_paydown_amount: "45",
	exit_debt_paydown: "15",
	exit_proceeds: "185",
	coc_return: "2.5",
	irr: "25",
	entry_mult_sensitivity: "1",
	exit_mult_sensitivity: "1"
)

deals << Deal.create(
	name: "Developer Town",
	city: "Austin",
	state: "TX",
	round_type: "millions",
	entry_year: "2015",
	entry_revenue: "40",
	entry_gp: "30",
	entry_gm: "75",
	entry_EBITDA: "20",
	entry_EBITDA_margin: "50",
	entry_capex: "0.5",
	entry_fcf: "19.5",
	leverage_multiple: "5",
	leverage_amount: "100",
	equity_multiple: "7",
	equity_amount: "140",
	purchase_multiple: "12",
	purchase_price: "240",
	exit_year: "2019",
	exit_revenue: "100",
	exit_gp: "80",
	exit_gm: "80",
	exit_EBITDA: "45",
	exit_EBITDA_margin: "45",
	exit_capex: "1",
	exit_fcf: "44",
	exit_multiple: "10",
	exit_price: "450",
	debt_paydown_multiple: "4.5",
	debt_paydown_amount: "90",
	exit_debt_paydown: "10",
	exit_proceeds: "440",
	coc_return: "3.1",
	irr: "35",
	entry_mult_sensitivity: "0.5",
	exit_mult_sensitivity: "1"
)

deals << Deal.create(
	name: "Xtreme Resorts",
	city: "Denver",
	state: "CO",
	round_type: "millions",
	entry_year: "2014",
	entry_revenue: "120",
	entry_gp: "40",
	entry_gm: "33.3",
	entry_EBITDA: "10",
	entry_EBITDA_margin: "8.3",
	entry_capex: "2",
	entry_fcf: "8",
	leverage_multiple: "3",
	leverage_amount: "30",
	equity_multiple: "5",
	equity_amount: "50",
	purchase_multiple: "8",
	purchase_price: "80",
	exit_year: "2019",
	exit_revenue: "200",
	exit_gp: "80",
	exit_gm: "40",
	exit_EBITDA: "30",
	exit_EBITDA_margin: "15",
	exit_capex: "5",
	exit_fcf: "25",
	exit_multiple: "10",
	exit_price: "250",
	debt_paydown_multiple: "3",
	debt_paydown_amount: "30",
	exit_debt_paydown: "0",
	exit_proceeds: "250",
	coc_return: "5",
	irr: "45",
	entry_mult_sensitivity: "1",
	exit_mult_sensitivity: "2"
)

deals << Deal.create(
	name: "Heartland Beer & Spirits",
	city: "Indianapolis",
	state: "IN",
	round_type: "millions",
	entry_year: "2015",
	entry_revenue: "50",
	entry_gp: "15",
	entry_gm: "30",
	entry_EBITDA: "7.5",
	entry_EBITDA_margin: "15",
	entry_capex: "2.5",
	entry_fcf: "5",
	leverage_multiple: "3",
	leverage_amount: "22.5",
	equity_multiple: "4",
	equity_amount: "30",
	purchase_multiple: "7",
	purchase_price: "52.5",
	exit_year: "2018",
	exit_revenue: "120",
	exit_gp: "40",
	exit_gm: "30",
	exit_EBITDA: "15",
	exit_EBITDA_margin: "12.5",
	exit_capex: "5",
	exit_fcf: "10",
	exit_multiple: "8",
	exit_price: "120",
	debt_paydown_multiple: "2",
	debt_paydown_amount: "15",
	exit_debt_paydown: "7.5",
	exit_proceeds: "112.5",
	coc_return: "3.8",
	irr: "40",
	entry_mult_sensitivity: "0.5",
	exit_mult_sensitivity: "0.5"
)
