# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

deals = []
deals << Deal.create(
	name: "ABC Industries",
	city: "San Francisco",
	state: "CA",
	round_type: "millions",
	entry_year: "2014",
	entry_revenue: "50",
	entry_gp: "25",
	entry_gm: "50",
	entry_EBITDA: "10",
	entry_EBITDA_margin: "20",
	entry_capex: "1",
	entry_fcf: "9",
	leverage_multiple: "5",
	leverage_amount: "50",
	equity_multiple: "5",
	equity_amount: "50",
	purchase_multiple: "10",
	purchase_price: "100",
	exit_year: "2018",
	exit_revenue: "100",
	exit_gp: "50",
	exit_gm: "50",
	exit_EBITDA: "25",
	exit_EBITDA_margin: "25",
	exit_capex: "3",
	exit_fcf: "22",
	exit_multiple: "10",
	exit_price: "250",
	debt_paydown_multiple: "3",
	debt_paydown_amount: "30",
	exit_debt_paydown: "20",
	exit_proceeds: "220",
	coc_return: "4.4",
	irr: "40",
	entry_mult_sensitivity: "1",
	exit_mult_sensitivity: "1"
)

deals << Deal.create(
	name: "Widgets, Inc.",
	city: "Chicago",
	state: "IL",
	round_type: "millions",
	entry_year: "2015",
	entry_revenue: "80",
	entry_gp: "30",
	entry_gm: "37.5",
	entry_EBITDA: "15",
	entry_EBITDA_margin: "18.8",
	entry_capex: "4",
	entry_fcf: "11",
	leverage_multiple: "4",
	leverage_amount: "60",
	equity_multiple: "5",
	equity_amount: "75",
	purchase_multiple: "9",
	purchase_price: "135",
	exit_year: "2019",
	exit_revenue: "120",
	exit_gp: "48",
	exit_gm: "40",
	exit_EBITDA: "30",
	exit_EBITDA_margin: "25",
	exit_capex: "5",
	exit_fcf: "20",
	exit_multiple: "8",
	exit_price: "200",
	debt_paydown_multiple: "3",
	debt_paydown_amount: "45",
	exit_debt_paydown: "15",
	exit_proceeds: "185",
	coc_return: "2.5",
	irr: "25",
	entry_mult_sensitivity: "1",
	exit_mult_sensitivity: "1"
)
